name: gardenmate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  android_intent_plus: ^5.0.2
  cloud_firestore: ^4.15.8
  device_info_plus: ^9.1.2
  esp_smartconfig: ^1.1.11
  firebase_database: ^10.4.9
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_bluetooth_serial: ^0.4.0
  flutter_local_notifications: ^17.2.1
  http: ^1.2.0
  intl_phone_number_input: ^0.7.4
  multicast_dns: ^0.3.2+6
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^5.0.0
  url_launcher: ^6.2.6
  wifi_info_flutter: ^2.0.2
  wifi_iot: ^0.3.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  the_apple_sign_in: ^1.1.1

flutter:
  uses-material-design: true
  assets: 
    - assets/Logo.png
    - assets/google.png
    - assets/apple1.png
  
