// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRzSJ0vA57W_YjGWQd9INX207j7O1mtY',
    appId: '1:266914060277:web:f71ee7606bf92b72a472bc',
    messagingSenderId: '266914060277',
    projectId: 'gardenmate-8a071',
    authDomain: 'gardenmate-8a071.firebaseapp.com',
    storageBucket: 'gardenmate-8a071.appspot.com',
    measurementId: 'G-NN49MND77Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOAzqnGn8C5toxv5aYRaIb-MZ8FhBlI8E',
    appId: '1:266914060277:android:c643bdd5f139b5f0a472bc',
    messagingSenderId: '266914060277',
    projectId: 'gardenmate-8a071',
    storageBucket: 'gardenmate-8a071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXO43B2Lq_2WXq0blTNO4KVbs5Xhr_pRE',
    appId: '1:266914060277:ios:aed771bfdf9bbd10a472bc',
    messagingSenderId: '266914060277',
    projectId: 'gardenmate-8a071',
    storageBucket: 'gardenmate-8a071.appspot.com',
    iosBundleId: 'com.example.gardenmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXO43B2Lq_2WXq0blTNO4KVbs5Xhr_pRE',
    appId: '1:266914060277:ios:aed771bfdf9bbd10a472bc',
    messagingSenderId: '266914060277',
    projectId: 'gardenmate-8a071',
    storageBucket: 'gardenmate-8a071.appspot.com',
    iosBundleId: 'com.example.gardenmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdRzSJ0vA57W_YjGWQd9INX207j7O1mtY',
    appId: '1:266914060277:web:bef2c9cbf5b7f497a472bc',
    messagingSenderId: '266914060277',
    projectId: 'gardenmate-8a071',
    authDomain: 'gardenmate-8a071.firebaseapp.com',
    storageBucket: 'gardenmate-8a071.appspot.com',
    measurementId: 'G-QQC3FGMECE',
  );
}
